<a href="https://colab.research.google.com/github/dilip-ksa/dilip_ml_pythondemo/blob/main/Day29_ML_Journey_MachineLearning_Day1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('homeprices.csv')

In [3]:
df.head()

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [4]:
df.describe()

area  bedrooms        age          price
count     6.000000   5.00000   6.000000       6.000000
mean   3416.666667   4.20000  16.500000  648333.333333
std     587.934237   1.30384   8.288546  109117.673484
min    2600.000000   3.00000   8.000000  550000.000000
25%    3050.000000   3.00000   9.750000  572500.000000
50%    3400.000000   4.00000  16.500000  602500.000000
75%    3900.000000   5.00000  19.500000  722500.000000
max    4100.000000   6.00000  30.000000  810000.000000

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   area      6 non-null      int64  
 1   bedrooms  5 non-null      float64
 2   age       6 non-null      int64  
 3   price     6 non-null      int64  
dtypes: float64(1), int64(3)
memory usage: 324.0 bytes


In [7]:
area = df.area
area

0    2600
1    3000
2    3200
3    3600
4    4000
5    4100
Name: area, dtype: int64

In [8]:
price = df.price
price

0    550000
1    565000
2    610000
3    595000
4    760000
5    810000
Name: price, dtype: int64

In [12]:
# create linear regression object
reg = linear_model.LinearRegression()
reg.fit(df[['area']],df.price)

LinearRegression()

In [15]:
reg.predict([[3300]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([628813.88621022])

In [16]:
reg.predict([[5000]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([913240.11571842])

In [17]:
reg.intercept_

np.float64(76692.38187078107)

In [18]:
reg.coef_

array([167.30954677])

In [19]:
# Manual calculation : y = mx + c
res = 167.30954677 * 3300 + 76692.38187078107
res

628813.8862117811