<a href="https://colab.research.google.com/github/dilip-ksa/dilip_ml_pythondemo/blob/main/Day24_ML_journey_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

arr = np.array([10,20,30,40]) # array element separated by space
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
[10 20 30 40]


In [4]:
lst = [10,20,30,40]
print(type(lst))
print(lst)

<class 'list'>
[10, 20, 30, 40]


In [5]:
arr = np.array([10,20,30,40, 'DEL']) # array element separated by space
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
['10' '20' '30' '40' 'DEL']


In [9]:
#Arithmatic operation on array
a1 = np.array([10,20,30,40]) # array element separated by space

print(a1)
a2 = a1 * 2
print(a2)

a3 = a2 / 4
print(a3)

a4 = a3 + 10.5
print(a4)

[10 20 30 40]
[20 40 60 80]
[ 5. 10. 15. 20.]
[15.5 20.5 25.5 30.5]


In [12]:
#Arithmatic operation on list
lst = [10,20,30,40]
print(lst)
lst2 = lst * 2
print(lst2)
lst3 = lst / 2
print(lst3)

[10, 20, 30, 40]
[10, 20, 30, 40, 10, 20, 30, 40]


TypeError: unsupported operand type(s) for -: 'list' and 'int'

In [16]:
#Memory usage numpy array and list
import sys
lst = [10,20,30,40,50,60]
print(sys.getsizeof(lst))

ar = np.array([10,20,30,40,50,60])
print(sys.getsizeof(ar))
print(ar.itemsize)
print(ar.nbytes)

104
160
8
48


In [20]:
# creating n dimentional array in numpy
ar1 = np.array([10,20,30,40])
print(ar1)
print(ar1.ndim)
print(ar1.shape)
print()
ar2 = np.array([[10,20,30,40],[50,60,70,80]])
print(ar2)
print(ar2.ndim)
print(ar2.shape)

print()
# zero dim array
ar3 = np.array(10)
print(ar3)
print(ar3.ndim)
print(ar3.shape)

print()
ar2 = np.array([[10,20,30,40]])
print(ar2)
print(ar2.ndim)
print(ar2.shape)

print()
ar2 = np.array([[[10,20,30,40]]])
print(ar2)
print(ar2.ndim)
print(ar2.shape)

[10 20 30 40]
1
(4,)

[[10 20 30 40]
 [50 60 70 80]]
2
(2, 4)

10
0
()

[[10 20 30 40]]
2
(1, 4)

[[[10 20 30 40]]]
3
(1, 1, 4)


In [21]:
# N dimentional
n = int(input("Enter dimention: "))
ar = np.array([10,20,30,40], ndmin=n)
print(ar)
print(ar.ndim)
print(ar.shape)

Enter dimention: 11
[[[[[[[[[[[10 20 30 40]]]]]]]]]]]
11
(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 4)


In [30]:
# properties of numpy array
ar = np.array([[10,20,30,40],[50,60,70,80]])
print("Array:",ar)
print("Dimention:",ar.ndim)
print("Shape:",ar.shape)
print("Size:",ar.size)
print("itemsize:",ar.itemsize)
print("MIN:",ar.min())
print("MAX:",ar.max())
print("SUM:",ar.sum())
print("NBYTES:",ar.nbytes)
print("ar.sum(axis=0):",ar.sum(axis=0))
print("ar.sum(axis=1):",ar.sum(axis=1))
print("SUM:",ar.mean())
print("SUM:",ar.std())
print("VAR:",ar.var())
print("argmin:",ar.argmin())
print("argmax:",ar.argmax())


Array: [[10 20 30 40]
 [50 60 70 80]]
Dimention: 2
Shape: (2, 4)
Size: 8
itemsize: 8
MIN: 10
MAX: 80
SUM: 360
NBYTES: 64
ar.sum(axis=0): [ 60  80 100 120]
ar.sum(axis=1): [100 260]
SUM: 45.0
SUM: 22.9128784747792
VAR: 525.0
argmin: 0
argmax: 7


In [31]:
# create a nd array
ar = np.zeros(4)
print(ar)
print(ar.ndim)
print(ar.shape)
print(ar.dtype)

[0. 0. 0. 0.]
1
(4,)
float64


In [33]:
# create a nd array
ar = np.zeros((4,3), dtype="int")
print(ar)
print(ar.ndim)
print(ar.shape)
print(ar.dtype)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
2
(4, 3)
int64


In [36]:
# create a nd array
ar = np.ones((4,3), dtype="int") * 2
print(ar)
print(ar.ndim)
print(ar.shape)
print(ar.dtype)
print(ar * 7)

[[2 2 2]
 [2 2 2]
 [2 2 2]
 [2 2 2]]
2
(4, 3)
int64
[[14 14 14]
 [14 14 14]
 [14 14 14]
 [14 14 14]]


In [40]:
#array with range
arr = np.arange(0,20,2, dtype='float')
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.dtype)

[ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18.]
1
(10,)
float64


In [52]:
#linspace in numpy
arr = np.linspace(1,10,5, dtype='float')
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.dtype)
nd_array = arr.reshape(5, 1)
print(nd_array)
print(nd_array.ndim)
print(nd_array.shape)
print(nd_array.dtype)

[ 1.    3.25  5.5   7.75 10.  ]
1
(5,)
float64
[[ 1.  ]
 [ 3.25]
 [ 5.5 ]
 [ 7.75]
 [10.  ]]
2
(5, 1)
float64


In [54]:
# numpy matrix
ar = np.matrix([[10,20,30,40],[50,60,70,80]])
print(ar)
print(type(ar))

print(ar.ndim)
print(ar.shape)
print(ar.dtype)

[[10 20 30 40]
 [50 60 70 80]]
<class 'numpy.matrix'>
2
(2, 4)
int64


In [55]:
# numpy matrix
mat = np.matrix([[10,20,30,40],[50,60,70,80]])
print(mat)
print(type(mat))
print(mat.ndim)
print(mat.shape)
print(mat.dtype)
print()
trns = mat.transpose()
print(trns)
print(trns.ndim)
print(trns.shape)
print(trns.dtype)
print()
trn = mat.T
print(trn)
print(trn.ndim)
print(trn.shape)
print(trn.dtype)

[[10 20 30 40]
 [50 60 70 80]]
<class 'numpy.matrix'>
2
(2, 4)
int64

[[10 50]
 [20 60]
 [30 70]
 [40 80]]
2
(4, 2)
int64

[[10 50]
 [20 60]
 [30 70]
 [40 80]]
2
(4, 2)
int64


In [56]:
# Identity
ar = np.identity(3, dtype='int')
print(ar)
print(ar.ndim)
print(ar.shape)
print(ar.dtype)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
2
(3, 3)
int64


In [57]:
#diagonal
ar = np.diag([10,20,30,40])
print(ar)
print(ar.ndim)
print(ar.shape)
print(ar.dtype)

[[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 40]]
2
(4, 4)
int64


In [61]:
ar3 = np.random.random(3)
print(ar3)

ar4 = np.random.randint(1,10, size=5)
print(ar4)

[0.28703332 0.2067439  0.27966773]
[7 5 3 7 3]


In [59]:
#random
ar = np.random.rand(3,3)
print(ar)
print(ar.ndim)
print(ar.shape)
print(ar.dtype)
print()

ar1 = np.random.randint(1,10, size=(3,3))
print(ar1)
print(ar1.ndim)
print(ar1.shape)
print(ar1.dtype)
print()

ar2 = np.random.randn(3,3)
print(ar2)
print(ar2.ndim)
print(ar2.shape)
print(ar2.dtype)
print()

ar3 = np.random.random((3,3))
print(ar3)
print(ar3.ndim)
print(ar3.shape)
print(ar3.dtype)

[[0.88107814 0.71124151 0.5053972 ]
 [0.45762915 0.22746483 0.85976479]
 [0.20540214 0.22251426 0.95437969]]
2
(3, 3)
float64

[[2 7 9]
 [2 9 1]
 [7 9 8]]
2
(3, 3)
int64

[[-0.84009296 -0.51332179  0.3219589 ]
 [ 0.79290867  0.7997451   0.40339445]
 [ 1.04368496  1.55114897 -0.01106741]]
2
(3, 3)
float64

[[0.82697306 0.27241839 0.4371694 ]
 [0.37519819 0.38876221 0.12040544]
 [0.77643224 0.7458416  0.1984059 ]]
2
(3, 3)
float64


In [67]:
r = np.random.uniform(1, 100, size=5)
print(r)
print()
r = np.random.uniform(1, 100, size=(5,5))
print(r)
print()
r = np.random.uniform(1, 100, size=(5,3))
print(r)

[58.07319986 85.66714996 14.39814729 81.03328706 42.69135243]

[[66.45352377 35.50723923 12.72485265 60.69904432 58.72543854]
 [45.11983361 93.2461593  40.24704731 39.55130551 18.5619229 ]
 [78.93975252  4.45536892  3.79533559 14.50305277 12.70833244]
 [21.56997676 15.78773437 89.30246014 71.44528824 63.2562767 ]
 [28.01373063 99.13694162 20.77207566  9.22551974 41.78752217]]

[[75.11564722 70.21238921 21.38417299]
 [76.9920677  34.30582018 92.03897586]
 [86.09128783 16.71131028 98.57396188]
 [56.15517881 13.34418992 72.58451303]
 [11.27788728 83.77309013 13.94606844]]
