<a href="https://colab.research.google.com/github/dilip-ksa/dilip_ml_pythondemo/blob/main/Day24_ML_journey_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

arr = np.array([10,20,30,40]) # array element separated by space
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
[10 20 30 40]


In [4]:
lst = [10,20,30,40]
print(type(lst))
print(lst)

<class 'list'>
[10, 20, 30, 40]


In [5]:
arr = np.array([10,20,30,40, 'DEL']) # array element separated by space
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
['10' '20' '30' '40' 'DEL']


In [9]:
#Arithmatic operation on array
a1 = np.array([10,20,30,40]) # array element separated by space

print(a1)
a2 = a1 * 2
print(a2)

a3 = a2 / 4
print(a3)

a4 = a3 + 10.5
print(a4)

[10 20 30 40]
[20 40 60 80]
[ 5. 10. 15. 20.]
[15.5 20.5 25.5 30.5]


In [12]:
#Arithmatic operation on list
lst = [10,20,30,40]
print(lst)
lst2 = lst * 2
print(lst2)
lst3 = lst / 2
print(lst3)

[10, 20, 30, 40]
[10, 20, 30, 40, 10, 20, 30, 40]


TypeError: unsupported operand type(s) for -: 'list' and 'int'

In [16]:
#Memory usage numpy array and list
import sys
lst = [10,20,30,40,50,60]
print(sys.getsizeof(lst))

ar = np.array([10,20,30,40,50,60])
print(sys.getsizeof(ar))
print(ar.itemsize)
print(ar.nbytes)

104
160
8
48


In [20]:
# creating n dimentional array in numpy
ar1 = np.array([10,20,30,40])
print(ar1)
print(ar1.ndim)
print(ar1.shape)
print()
ar2 = np.array([[10,20,30,40],[50,60,70,80]])
print(ar2)
print(ar2.ndim)
print(ar2.shape)

print()
# zero dim array
ar3 = np.array(10)
print(ar3)
print(ar3.ndim)
print(ar3.shape)

print()
ar2 = np.array([[10,20,30,40]])
print(ar2)
print(ar2.ndim)
print(ar2.shape)

print()
ar2 = np.array([[[10,20,30,40]]])
print(ar2)
print(ar2.ndim)
print(ar2.shape)

[10 20 30 40]
1
(4,)

[[10 20 30 40]
 [50 60 70 80]]
2
(2, 4)

10
0
()

[[10 20 30 40]]
2
(1, 4)

[[[10 20 30 40]]]
3
(1, 1, 4)


In [21]:
# N dimentional
n = int(input("Enter dimention: "))
ar = np.array([10,20,30,40], ndmin=n)
print(ar)
print(ar.ndim)
print(ar.shape)

Enter dimention: 11
[[[[[[[[[[[10 20 30 40]]]]]]]]]]]
11
(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 4)


In [30]:
# properties of numpy array
ar = np.array([[10,20,30,40],[50,60,70,80]])
print("Array:",ar)
print("Dimention:",ar.ndim)
print("Shape:",ar.shape)
print("Size:",ar.size)
print("itemsize:",ar.itemsize)
print("MIN:",ar.min())
print("MAX:",ar.max())
print("SUM:",ar.sum())
print("NBYTES:",ar.nbytes)
print("ar.sum(axis=0):",ar.sum(axis=0))
print("ar.sum(axis=1):",ar.sum(axis=1))
print("SUM:",ar.mean())
print("SUM:",ar.std())
print("VAR:",ar.var())
print("argmin:",ar.argmin())
print("argmax:",ar.argmax())


Array: [[10 20 30 40]
 [50 60 70 80]]
Dimention: 2
Shape: (2, 4)
Size: 8
itemsize: 8
MIN: 10
MAX: 80
SUM: 360
NBYTES: 64
ar.sum(axis=0): [ 60  80 100 120]
ar.sum(axis=1): [100 260]
SUM: 45.0
SUM: 22.9128784747792
VAR: 525.0
argmin: 0
argmax: 7


In [31]:
# create a nd array
ar = np.zeros(4)
print(ar)
print(ar.ndim)
print(ar.shape)
print(ar.dtype)

[0. 0. 0. 0.]
1
(4,)
float64


In [33]:
# create a nd array
ar = np.zeros((4,3), dtype="int")
print(ar)
print(ar.ndim)
print(ar.shape)
print(ar.dtype)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
2
(4, 3)
int64


In [36]:
# create a nd array
ar = np.ones((4,3), dtype="int") * 2
print(ar)
print(ar.ndim)
print(ar.shape)
print(ar.dtype)
print(ar * 7)

[[2 2 2]
 [2 2 2]
 [2 2 2]
 [2 2 2]]
2
(4, 3)
int64
[[14 14 14]
 [14 14 14]
 [14 14 14]
 [14 14 14]]
