<a href="https://colab.research.google.com/github/dilip-ksa/dilip_ml_pythondemo/blob/main/Day25_ML_journey_Panda1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

arr = np.array([10,20,30,40]) # array element separated by space
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
[10 20 30 40]


In [ ]:
lst = [10,20,30,40]
print(type(lst))
print(lst)

<class 'list'>
[10, 20, 30, 40]


In [ ]:
arr = np.array([10,20,30,40, 'DEL']) # array element separated by space
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
['10' '20' '30' '40' 'DEL']


In [ ]:
#Arithmatic operation on array
a1 = np.array([10,20,30,40]) # array element separated by space

print(a1)
a2 = a1 * 2
print(a2)

a3 = a2 / 4
print(a3)

a4 = a3 + 10.5
print(a4)

[10 20 30 40]
[20 40 60 80]
[ 5. 10. 15. 20.]
[15.5 20.5 25.5 30.5]


In [ ]:
#Arithmatic operation on list
lst = [10,20,30,40]
print(lst)
lst2 = lst * 2
print(lst2)
lst3 = lst / 2
print(lst3)

[10, 20, 30, 40]
[10, 20, 30, 40, 10, 20, 30, 40]


TypeError: unsupported operand type(s) for -: 'list' and 'int'

In [ ]:
#Memory usage numpy array and list
import sys
lst = [10,20,30,40,50,60]
print(sys.getsizeof(lst))

ar = np.array([10,20,30,40,50,60])
print(sys.getsizeof(ar))
print(ar.itemsize)
print(ar.nbytes)

104
160
8
48


In [ ]:
# creating n dimentional array in numpy
ar1 = np.array([10,20,30,40])
print(ar1)
print(ar1.ndim)
print(ar1.shape)
print()
ar2 = np.array([[10,20,30,40],[50,60,70,80]])
print(ar2)
print(ar2.ndim)
print(ar2.shape)

print()
# zero dim array
ar3 = np.array(10)
print(ar3)
print(ar3.ndim)
print(ar3.shape)

print()
ar2 = np.array([[10,20,30,40]])
print(ar2)
print(ar2.ndim)
print(ar2.shape)

print()
ar2 = np.array([[[10,20,30,40]]])
print(ar2)
print(ar2.ndim)
print(ar2.shape)

[10 20 30 40]
1
(4,)

[[10 20 30 40]
 [50 60 70 80]]
2
(2, 4)

10
0
()

[[10 20 30 40]]
2
(1, 4)

[[[10 20 30 40]]]
3
(1, 1, 4)


In [ ]:
# N dimentional
n = int(input("Enter dimention: "))
ar = np.array([10,20,30,40], ndmin=n)
print(ar)
print(ar.ndim)
print(ar.shape)

Enter dimention: 11
[[[[[[[[[[[10 20 30 40]]]]]]]]]]]
11
(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 4)


In [ ]:
# properties of numpy array
ar = np.array([[10,20,30,40],[50,60,70,80]])
print("Array:",ar)
print("Dimention:",ar.ndim)
print("Shape:",ar.shape)
print("Size:",ar.size)
print("itemsize:",ar.itemsize)
print("MIN:",ar.min())
print("MAX:",ar.max())
print("SUM:",ar.sum())
print("NBYTES:",ar.nbytes)
print("ar.sum(axis=0):",ar.sum(axis=0))
print("ar.sum(axis=1):",ar.sum(axis=1))
print("SUM:",ar.mean())
print("SUM:",ar.std())
print("VAR:",ar.var())
print("argmin:",ar.argmin())
print("argmax:",ar.argmax())


Array: [[10 20 30 40]
 [50 60 70 80]]
Dimention: 2
Shape: (2, 4)
Size: 8
itemsize: 8
MIN: 10
MAX: 80
SUM: 360
NBYTES: 64
ar.sum(axis=0): [ 60  80 100 120]
ar.sum(axis=1): [100 260]
SUM: 45.0
SUM: 22.9128784747792
VAR: 525.0
argmin: 0
argmax: 7


In [ ]:
# create a nd array
ar = np.zeros(4)
print(ar)
print(ar.ndim)
print(ar.shape)
print(ar.dtype)

[0. 0. 0. 0.]
1
(4,)
float64


In [ ]:
# create a nd array
ar = np.zeros((4,3), dtype="int")
print(ar)
print(ar.ndim)
print(ar.shape)
print(ar.dtype)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
2
(4, 3)
int64


In [ ]:
# create a nd array
ar = np.ones((4,3), dtype="int") * 2
print(ar)
print(ar.ndim)
print(ar.shape)
print(ar.dtype)
print(ar * 7)

[[2 2 2]
 [2 2 2]
 [2 2 2]
 [2 2 2]]
2
(4, 3)
int64
[[14 14 14]
 [14 14 14]
 [14 14 14]
 [14 14 14]]


In [ ]:
#array with range
arr = np.arange(0,20,2, dtype='float')
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.dtype)

[ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18.]
1
(10,)
float64


In [ ]:
#linspace in numpy
arr = np.linspace(1,10,5, dtype='float')
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.dtype)
nd_array = arr.reshape(5, 1)
print(nd_array)
print(nd_array.ndim)
print(nd_array.shape)
print(nd_array.dtype)

[ 1.    3.25  5.5   7.75 10.  ]
1
(5,)
float64
[[ 1.  ]
 [ 3.25]
 [ 5.5 ]
 [ 7.75]
 [10.  ]]
2
(5, 1)
float64


In [ ]:
# numpy matrix
ar = np.matrix([[10,20,30,40],[50,60,70,80]])
print(ar)
print(type(ar))

print(ar.ndim)
print(ar.shape)
print(ar.dtype)

[[10 20 30 40]
 [50 60 70 80]]
<class 'numpy.matrix'>
2
(2, 4)
int64


In [ ]:
# numpy matrix
mat = np.matrix([[10,20,30,40],[50,60,70,80]])
print(mat)
print(type(mat))
print(mat.ndim)
print(mat.shape)
print(mat.dtype)
print()
trns = mat.transpose()
print(trns)
print(trns.ndim)
print(trns.shape)
print(trns.dtype)
print()
trn = mat.T
print(trn)
print(trn.ndim)
print(trn.shape)
print(trn.dtype)

[[10 20 30 40]
 [50 60 70 80]]
<class 'numpy.matrix'>
2
(2, 4)
int64

[[10 50]
 [20 60]
 [30 70]
 [40 80]]
2
(4, 2)
int64

[[10 50]
 [20 60]
 [30 70]
 [40 80]]
2
(4, 2)
int64


In [ ]:
# Identity
ar = np.identity(3, dtype='int')
print(ar)
print(ar.ndim)
print(ar.shape)
print(ar.dtype)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
2
(3, 3)
int64


In [ ]:
#diagonal
ar = np.diag([10,20,30,40])
print(ar)
print(ar.ndim)
print(ar.shape)
print(ar.dtype)

[[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 40]]
2
(4, 4)
int64


In [ ]:
ar3 = np.random.random(3)
print(ar3)

ar4 = np.random.randint(1,10, size=5)
print(ar4)

[0.28703332 0.2067439  0.27966773]
[7 5 3 7 3]


In [ ]:
#random
ar = np.random.rand(3,3)
print(ar)
print(ar.ndim)
print(ar.shape)
print(ar.dtype)
print()

ar1 = np.random.randint(1,10, size=(3,3))
print(ar1)
print(ar1.ndim)
print(ar1.shape)
print(ar1.dtype)
print()

ar2 = np.random.randn(3,3)
print(ar2)
print(ar2.ndim)
print(ar2.shape)
print(ar2.dtype)
print()

ar3 = np.random.random((3,3))
print(ar3)
print(ar3.ndim)
print(ar3.shape)
print(ar3.dtype)

[[0.88107814 0.71124151 0.5053972 ]
 [0.45762915 0.22746483 0.85976479]
 [0.20540214 0.22251426 0.95437969]]
2
(3, 3)
float64

[[2 7 9]
 [2 9 1]
 [7 9 8]]
2
(3, 3)
int64

[[-0.84009296 -0.51332179  0.3219589 ]
 [ 0.79290867  0.7997451   0.40339445]
 [ 1.04368496  1.55114897 -0.01106741]]
2
(3, 3)
float64

[[0.82697306 0.27241839 0.4371694 ]
 [0.37519819 0.38876221 0.12040544]
 [0.77643224 0.7458416  0.1984059 ]]
2
(3, 3)
float64


In [ ]:
r = np.random.uniform(1, 100, size=5)
print(r)
print()
r = np.random.uniform(1, 100, size=(5,5))
print(r)
print()
r = np.random.uniform(1, 100, size=(5,3))
print(r)

[58.07319986 85.66714996 14.39814729 81.03328706 42.69135243]

[[66.45352377 35.50723923 12.72485265 60.69904432 58.72543854]
 [45.11983361 93.2461593  40.24704731 39.55130551 18.5619229 ]
 [78.93975252  4.45536892  3.79533559 14.50305277 12.70833244]
 [21.56997676 15.78773437 89.30246014 71.44528824 63.2562767 ]
 [28.01373063 99.13694162 20.77207566  9.22551974 41.78752217]]

[[75.11564722 70.21238921 21.38417299]
 [76.9920677  34.30582018 92.03897586]
 [86.09128783 16.71131028 98.57396188]
 [56.15517881 13.34418992 72.58451303]
 [11.27788728 83.77309013 13.94606844]]


In [ ]:
# Random choice
k = np.random.choice([10,20,30,40,50,60])
print(k)

k = np.random.choice([10,20,30,40,50,60], size=3)
print(k)

k = np.random.choice([10,20,30,40,50,60], size=(3,3))
print(k)

10
[60 40 20]
[[50 60 20]
 [60 50 30]
 [60 30 50]]


In [ ]:
# Random choice - without duplicate, default value True
k = np.random.choice([10,20,30,40,50,60, 20, 30,10, 50], size=3, replace=False)
print(k)

k = np.random.choice([10,20,30,40,50,60, 20, 30,10, 50], size=(3, 3), replace=False)
print(k)

[50 20 60]
[[20 30 30]
 [50 50 60]
 [40 10 20]]


In [ ]:
# Probability array
a = np.array([22,33,55])
prob = np.array([.5, .2, .3])
k = np.random.choice(a, p=prob, size=10)
print(k)

k = np.random.choice(a, p=prob, size=(3,3))
print(k)

[22 55 22 22 55 55 22 55 33 33]
[[22 55 22]
 [22 22 22]
 [33 55 33]]


In [ ]:
# choosing random rows
arr_2d = np.arange(0,20).reshape(4,5)
print(arr_2d)
print()
rw = arr_2d.shape[0]
col = arr_2d.shape[1]
print(rw, col)
print()
row_index = np.random.choice(rw, size=2, replace=False)
print(row_index)
print()

final_res = arr_2d[row_index]
print(final_res)

print()
col_index = np.random.choice(col, size=3, replace=False)
print(col_index)
print()

final_res = arr_2d[:, col_index]
print(final_res)

print()
final_res = arr_2d[-2:, col_index]
print(final_res)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

4 5

[3 2]

[[15 16 17 18 19]
 [10 11 12 13 14]]

[3 1 0]

[[ 3  1  0]
 [ 8  6  5]
 [13 11 10]
 [18 16 15]]

[[13 11 10]
 [18 16 15]]


In [ ]:
#shuffle the array
a = np.arange(10)
print(a)
b = a.copy()
np.random.shuffle(b)
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[1 6 5 3 9 2 8 7 4 0]


In [ ]:
# shuffle with permutation
a = np.arange(10)
print(a)
b = np.random.permutation(a)
print(b)


c = np.random.permutation(10)
print(c)

[0 1 2 3 4 5 6 7 8 9]
[9 7 0 2 4 5 1 6 3 8]
[2 3 6 4 7 9 5 1 8 0]


In [ ]:
# permutation with 2d array, only row are shuffle
ar = np.arange(0, 20).reshape(4,5)
print(ar)
print()
b = np.random.permutation(ar)
print(b)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

[[ 0  1  2  3  4]
 [15 16 17 18 19]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [ ]:
# permutation with 2d array, all element are shuffle
ar = np.random.permutation(20).reshape(4,5)
print(ar)
print()

[[18  3 10 14  9]
 [12  6  5  1  2]
 [15 11 13 17 16]
 [ 0  8  4  7 19]]



In [ ]:
ar = np.arange(0, 20).reshape(4,5)
print(ar)
print()
rw_no = ar.shape[0]
col_no = ar.shape[1]
print(rw_no, col_no)
print()
shuffled_index = np.random.permutation(rw_no)
print(shuffled_index)
print()
final_res = ar[shuffled_index]
print(final_res)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

4 5

[0 3 1 2]

[[ 0  1  2  3  4]
 [15 16 17 18 19]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [ ]:
# grouping and spliting
arr_1d = np.arange(5)
print(arr_1d)
print()
arr_1d_1 = np.arange(5, 10)
print(arr_1d_1)
print()
arr_2d_0 = np.arange(0,18).reshape(3,6)
print(arr_2d_0)
print()
arr_2d_1 = np.arange(18,36).reshape(3,6)
print(arr_2d_1)
print()

[0 1 2 3 4]

[5 6 7 8 9]

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]

[[18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]



In [ ]:
# cocatenate array - row wise(axis=0)
ar = np.concatenate([arr_1d, arr_1d_1])
print(ar)
print()
ar = np.concatenate([arr_2d_0, arr_2d_1])
print(ar)
print()

[0 1 2 3 4 5 6 7 8 9]

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]



In [ ]:
# cocatenate array - col wise

#ar = np.concatenate([arr_1d, arr_1d_1], axis=1) # error for 1d array
#print(ar)
print()

ar = np.concatenate([arr_2d_0, arr_2d_1], axis=1)
print(ar)
print()



[[ 0  1  2  3  4  5 18 19 20 21 22 23]
 [ 6  7  8  9 10 11 24 25 26 27 28 29]
 [12 13 14 15 16 17 30 31 32 33 34 35]]



In [ ]:
# numpy stack
ar = np.stack([arr_1d, arr_1d_1])
print(ar)
print()

ar = np.stack([arr_1d, arr_1d_1], axis=1)
print(ar)
print()

ar = np.stack([arr_1d_1, arr_1d])
print(ar)
print()


[[0 1 2 3 4]
 [5 6 7 8 9]]

[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]

[[5 6 7 8 9]
 [0 1 2 3 4]]



In [ ]:
#2d array stacking
ar = np.stack([arr_2d_0, arr_2d_1])
print(ar)
print(ar.ndim)
print(ar.shape)
print()

# column stacking
ar = np.stack([arr_2d_0, arr_2d_1], axis=1)
print(ar)
print(ar.ndim)
print(ar.shape)
print()

# column stacking
ar = np.stack([arr_2d_0, arr_2d_1], axis=-1)
print(ar)
print(ar.ndim)
print(ar.shape)
print()

# column stacking
ar = np.stack([arr_2d_0, arr_2d_1], axis=-3)
print(ar)
print(ar.ndim)
print(ar.shape)
print()

[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]]

 [[18 19 20 21 22 23]
  [24 25 26 27 28 29]
  [30 31 32 33 34 35]]]
3
(2, 3, 6)

[[[ 0  1  2  3  4  5]
  [18 19 20 21 22 23]]

 [[ 6  7  8  9 10 11]
  [24 25 26 27 28 29]]

 [[12 13 14 15 16 17]
  [30 31 32 33 34 35]]]
3
(3, 2, 6)

[[[ 0 18]
  [ 1 19]
  [ 2 20]
  [ 3 21]
  [ 4 22]
  [ 5 23]]

 [[ 6 24]
  [ 7 25]
  [ 8 26]
  [ 9 27]
  [10 28]
  [11 29]]

 [[12 30]
  [13 31]
  [14 32]
  [15 33]
  [16 34]
  [17 35]]]
3
(3, 6, 2)

[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]]

 [[18 19 20 21 22 23]
  [24 25 26 27 28 29]
  [30 31 32 33 34 35]]]
3
(2, 3, 6)



In [ ]:
# vertical stack
ar = np.vstack([arr_2d_0, arr_2d_1])
print(ar)
print(ar.ndim)
print(ar.shape)
print()

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
2
(6, 6)



In [ ]:
# horizontal stack
ar = np.hstack([arr_2d_0, arr_2d_1])
print(ar)
print(ar.ndim)
print(ar.shape)
print()

[[ 0  1  2  3  4  5 18 19 20 21 22 23]
 [ 6  7  8  9 10 11 24 25 26 27 28 29]
 [12 13 14 15 16 17 30 31 32 33 34 35]]
2
(3, 12)



In [ ]:
# spliting array - 1d
arr_1d = np.arange(10)
print(arr_1d)
print()

k = np.split(arr_1d, indices_or_sections=2)
print(k)
print()

k = np.split(arr_1d, indices_or_sections=[2, 5, 7])
print(k)
print()


[0 1 2 3 4 5 6 7 8 9]

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

[array([0, 1]), array([2, 3, 4]), array([5, 6]), array([7, 8, 9])]



In [ ]:
#split 2d array
arr_2d = np.arange(0,18).reshape(3,6)
print(arr_2d)
print()

k = np.split(arr_2d, indices_or_sections=3, axis=0)
print(k)
print()

k = np.split(arr_2d, indices_or_sections=3, axis=1)
print(k)
print()

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]

[array([[0, 1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10, 11]]), array([[12, 13, 14, 15, 16, 17]])]

[array([[ 0,  1],
       [ 6,  7],
       [12, 13]]), array([[ 2,  3],
       [ 8,  9],
       [14, 15]]), array([[ 4,  5],
       [10, 11],
       [16, 17]])]



In [ ]:
# expanding

In [ ]:
# squeeze

In [ ]:
# reordering

In [ ]:
# flip in 2d array
print(arr_2d)
print()
k = np.flip(arr_2d)
print(k)
print()
k = np.flip(arr_2d, axis=1)
print(k)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]

[[17 16 15 14 13 12]
 [11 10  9  8  7  6]
 [ 5  4  3  2  1  0]]

[[ 5  4  3  2  1  0]
 [11 10  9  8  7  6]
 [17 16 15 14 13 12]]


In [ ]:
# resize
print(arr_2d)
print()
k = np.resize(arr_2d, new_shape=13)
print(k)
print()
k = np.resize(arr_2d, new_shape=(6,3))
print(k)
print()
k = np.resize(arr_2d, (3, 5))
print(k)
print()
k = np.resize(arr_2d, new_shape=(3,5,3))
print(k)
print()

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]

[ 0  1  2  3  4  5  6  7  8  9 10 11 12]

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]]

